- alias: "Power state on HA start-up"
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: mqtt.publish
      data:
        topic: "cmnd/p0/power"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/s1/power1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/s1/power2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/s1/power3"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/s1/power4"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/s0/power1"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/s0/power2"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/s0/power3"
        payload: "" 
    - service: mqtt.publish
      data:
        topic: "cmnd/s0/power4"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/TelePeriod"
        payload: "60"
    - service: mqtt.publish
      data:
        topic: "cmnd/sonoff/TelePeriod"
        payload: "100"
    - service: mqtt.publish
      data:
        topic: "cmnd/temp0/TelePeriod"
        payload: "60"
    - service: mqtt.publish
      data:
        topic: "cmnd/temp0/TelePeriod"
        payload: "100"
    - service: mqtt.publish
      data:
        topic: "cmnd/alarm/TelePeriod"
        payload: "60"
    - service: mqtt.publish
      data:
        topic: "cmnd/basic1/power"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/basic0/power"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/b0/power"
        payload: ""
    - service: mqtt.publish
      data:
        topic: "cmnd/b0/TelePeriod"
        payload: "30"
    - service: mqtt.publish
      data:
        topic: "cmnd/water_out/TelePeriod"
        payload: "60"


