homeassistant:
  customize:
    switch.b0:
      friendly_name: Boiler
      icon: mdi:shower
    
    sensor.btemp0:
      friendly_name: Boiler Temperator 
      icon: mdi:oil-temperature

group: 

  bolier_group:
    name: Boiler
    entities:
      - sensor.btemp0
      - switch.b0
      - input_boolean.boiler_auto_enable
      - input_number.boiler_timer_time
      - input_number.boiler_temp_min
      - input_number.boiler_temp_max
      - history_graph.boiler_graph
      - sensor.boiler_total_hours
      - sensor.boiler_total_hours2
      - sensor.stats_mean

  Boiler:
    name: Boiler
    view: yes
    icon: mdi:shower
    entities:
      - sensor.btemp0
      - group.bolier_group
      - sensor.stats_mean


input_boolean:
  boiler_auto_enable:
    name: Enable auto


input_number:
  boiler_timer_time:
    name: Bolier Timer
    min: 10
    max: 120
    step: 10
  boiler_temp_min:
    name: min-temp
    min: 25.0
    max: 40.0
    step: 1.0
  boiler_temp_max:
    name: max-temp
    min: 32.0
    max: 60.0
    step: 1.0


switch:

  - platform: tasmota
    name: b0
    stopic: b0

sensor:

  - platform: mqtt
    name: "btemp0"
    state_topic: "tele/b0/SENSOR"
    value_template: "{{value_json['DS18B20'].Temperature }}"
    qos: 1
    unit_of_measurement : "C" 
  
  - platform: statistics
    entity_id: sensor.btemp0
    max_age:
      minutes: 600

  - platform: accumulator
    name: boiler_total_hours2
    entity_id: switch.b0
    state_on: 'on'
    state_off: 'off'

  
  - platform: history_stats
    name: boiler_total_hours
    entity_id: switch.b0
    state: 'on'
    type: time
    start: '{{ now().replace(hour=0).replace(minute=0).replace(second=0) }}'
    duration:
       days: 7
  
  - platform: template
    sensors:
      boiler_eff_power0:
        friendly_name: 'Boiler power-ef C/hour'
        unit_of_measurement: "C"
        value_template: "{{ states('sensor.boiler_eff_power0') }}"
      boiler_eff_solar0:
        friendly_name: 'Boiler solar-ef C/hour'
        unit_of_measurement: "C"
        value_template: "{{ states('sensor.boiler_eff_solar0') }}"


history_graph:
  gr2:
    name: Boiler Graph
    hours_to_show: 24
    entities:
       - sensor.btemp0
       - switch.b0


