
sensor:

  - platform: tasmota
    name: water_total
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (45497 + (value))|int }}"

  - platform: tasmota
    name: water_total_external
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (80600 + 45497 + (value))|int }}"

  - platform: tasmota
    name: water_total_norm
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (37950 + (value/1.21))|int }}"

  - platform: tasmota
    name: water_total_external_norm
    stopic: water_out
    id: 1
    unit_of_measurement: 'l'
    icon: mdi:water-pump
    expire_after: 300
    value_template: "{{ (80600 + 37950 + (value/1.21))|int }}"
    
    #updated by the water app
  - platform: template
    sensors:
      # shows only 1 liters 
      water_leak_detector: 
        friendly_name: 'water leaks detector'
        unit_of_measurement: "l"
        value_template: "{{ states('sensor.water_leak_detector') }}"
      
      # shows bulks of water in total        
      water_bursts:
        friendly_name: 'water usage in bulks'
        unit_of_measurement: "l"
        value_template: "{{ states('sensor.water_bursts') }}"



